### ISSUE TITLE
Forward traffic from NLB to Layer 7 ingress-nginx

### ISSUE THREAD

**Issue by BernhardFuchs** [exoscale/exoscale-cloud-controller-manager#20]
I've setup a cluster with kubernetes [ingress-nginx](https://kubernetes.github.io/ingress-nginx/deploy/#using-helm) installed via helm and try to route the traffic to that as suggested in a ticket by your support team. The problem is that the `ingress-nginx-controller` type `LoadBalancer` never gets an IP assigned.

First I created a `LoadBalancer` inside the namespace of the app the traffic should be routed to eventually:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-http
  annotations:
    service.beta.kubernetes.io/exoscale-loadbalancer-zone: "at-vie-1"
spec:
  selector:
    app: app-name
  type: LoadBalancer
  ports:
    - port: 80
```

Then I tried to override the auto-created `ingress-nginx-controller` which results in a kubectl error:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  annotations:
    service.beta.kubernetes.io/exoscale-loadbalancer-zone: "at-vie-1"
spec:
  selector:
    app: ingress-nginx
  type: LoadBalancer
  ports:
    - port: 80
```

`kubectl -n ingress-nginx get all` give following output:
```
NAME                                            READY   STATUS    RESTARTS   AGE
pod/ingress-nginx-controller-777d688cbf-bzrxt   1/1     Running   0          114m

NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/ingress-nginx-controller             LoadBalancer   10.43.169.39    <pending>     80:30554/TCP,443:32422/TCP   114m
service/ingress-nginx-controller-admission   ClusterIP      10.43.202.131   <none>        443/TCP                      114m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-nginx-controller   1/1     1            1           114m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-nginx-controller-777d688cbf   1         1         1       114m
```

Atm `kubectl -n ingress-nginx describe svc ingress-nginx-controller` returns the following:
```
Name:                     ingress-nginx-controller
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/component=controller
                          app.kubernetes.io/instance=ingress-nginx
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/version=0.40.2
                          helm.sh/chart=ingress-nginx-3.7.1
Annotations:              meta.helm.sh/release-name: ingress-nginx
                          meta.helm.sh/release-namespace: ingress-nginx
                          service.beta.kubernetes.io/exoscale-loadbalancer-zone: at-vie-1
Selector:                 app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx,app=ingress-nginx
Type:                     LoadBalancer
IP:                       10.43.169.39
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30554/TCP
Endpoints:                <none>
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  32422/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                 From                Message
  ----     ------                  ----                ----                -------
  Warning  SyncLoadBalancerFailed  16m (x19 over 81m)  service-controller  Error syncing load balancer: failed to ensure load balancer: zone not specified either in annotations or in the controller default zone configuration
  Normal   EnsuringLoadBalancer    92s (x22 over 81m)  service-controller  Ensuring load balancer
```

The annotation for the exoscale LoadBalancer is there but it doesn't get an IP.
